### ISSUE TITLE
Maxmind key

### ISSUE THREAD

**Issue by tgreggs** [mschmitt/GeoLite2xtables#11]
Any chance you could update your GeoLite2xtables to include the configurability of Maxmind account and key?

Thanks,
Tracy

**Comment by haikubox** [comment]
Hi Tracy,
You could just patch [00_download_geolite2](https://github.com/mschmitt/GeoLite2xtables/blob/master/00_download_geolite2) script yourself and change the download link at line 4 to something like this:

`GEOLITEURL='https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=YOUR_LICENSE_KEY&suffix=zip'`

More details on how to properly build the direct download link you can find on [MaxMind site](https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads).

**Comment by tgreggs** [comment]
Thank you!
