### ISSUE TITLE
Privacy regulations and accessing GeoLite2 databases after December 30, 2019

### ISSUE THREAD

**Issue by TrekPL** [mschmitt/GeoLite2xtables#9]
As written  [here](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) they have changed the way of accessing that DB and script cannot download it. Can you update it and add extra config fields so everybody can use it?

**Comment by Twilight-Networks** [comment]
Simple Solution:

Edit the Script `00_download_geolite2` and change the Variable `GEOLITEURL` to:

`https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=LICENSEKEY&suffix=zip`

(Make sure that you replace LICENSEKEY with your own MaxMind-Licensekey)

**Comment by TrekPL** [comment]
Working like a charm :)
